{
 "title": "Http Loader",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Http Runner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.http.request.success.count, 5)"
    },
    {
     "target": "aliasByNode(app.gelerion.local.http.request.failure.count, 5)"
    }
   ]
  },
  {
   "title": "Mean Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.http.response-time.new-ms.mean, 5)"
    },
    {
     "target": "aliasByNode(app.gelerion.local.http.response-time.old-ms.mean, 5)"
    }
   ]
  },
  {
   "title": "Mean Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.http.response-time.new-ms.mean, 5)"
    },
    {
     "target": "aliasByNode(app.gelerion.local.http.response-time.old-ms.mean, 5)"
    }
   ]
  },
  {
   "title": "P95 Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.http.response-time.new-ms.p95, 5)"
    },
    {
     "target": "aliasByNode(app.gelerion.local.http.response-time.old-ms.p95, 5)"
    }
   ]
  },
  {
   "title": "P99 Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.http.response-time.new-ms.p99, 5)"
    },
    {
     "target": "aliasByNode(app.gelerion.local.http.response-time.old-ms.p99, 5)"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.http.response-time.new-ms.max, 5)"
    },
    {
     "target": "aliasByNode(app.gelerion.local.http.response-time.old-ms.max, 5)"
    }
   ]
  },
  { "title": "Scheduling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Scheduler Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(app.gelerion.local.scheduler.queue.size, 'queue-size')"
    },
    {
     "target": "aliasByNode(app.gelerion.local.scheduler.execution.task-count, 5)"
    },
    {
     "target": "aliasByNode(app.gelerion.local.scheduler.execution.completed-task-count, 5)"
    }
   ]
  },
  {
   "title": "Scheduler Poll Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.scheduler.execution.pool-size, 5)"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.scheduling.execution.accuracy-ms.mean, 5)"
    }
   ]
  },
  {
   "title": "Scheduling Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.scheduling.status.*.m1_rate, 5)"
    }
   ]
  },
  {
   "title": "Delay TIme",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.scheduling.time.delay-ms.{mean,max}, 5, 6)"
    }
   ]
  },
  {
   "title": "Execution Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.scheduling.execution.executed.count, 5)"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Consumer Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(app.gelerion.local.kafka.consumer.produced.m1_rate, 5)"
    }
   ]
  },
  {
   "title": "Consumer Batch Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(app.gelerion.local.kafka.consumer.consumed.mean, 'batchSize')"
    }
   ]
  }
 ]
}